services:
  pipeline:
    image: "aapashkov/generic-amr:0.3.0"
    working_dir: "/ext"
    user: "${UID}:${GID}"
    volumes:
      - "./:/ext"
    command: /bin/bash -euo pipefail -c \
      "trap 'rm -rf data/*/.tmp.*' EXIT && make -j${JOBS:-$(nproc)}"
